apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-deploy-svc
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: nginx
  type: ClusterIP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: ubuntu-20-gf-kube-master
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-deploy-svc
            port:
              number: 80

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
data:
  proxy-protocol: "True"
  real-ip-header: "proxy_protocol"
  set-real-ip-from: "0.0.0.0"


    
